//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prevu.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prevu.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SYS_24VPWR_CAB_OFF.
        /// </summary>
        internal static string _SYS_24VPWR_CAB_OFF {
            get {
                return ResourceManager.GetString("_SYS_24VPWR_CAB_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        internal static string ACKNOWLEDGE {
            get {
                return ResourceManager.GetString("ACKNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge All.
        /// </summary>
        internal static string ACKNOWLEDGE_ALL {
            get {
                return ResourceManager.GetString("ACKNOWLEDGE ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string ACTUAL {
            get {
                return ResourceManager.GetString("ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Wireless Card.
        /// </summary>
        internal static string CHANGE_WIRELESS_CARD {
            get {
                return ResourceManager.GetString("CHANGE WIRELESS CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        internal static string CHOOSE_DATE {
            get {
                return ResourceManager.GetString("CHOOSE DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the action.
        /// </summary>
        internal static string CHOOSE_THE_ACTION {
            get {
                return ResourceManager.GetString("CHOOSE THE ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Trends.
        /// </summary>
        internal static string CHOOSE_TRENDS {
            get {
                return ResourceManager.GetString("CHOOSE TRENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string CLEAR_ALL {
            get {
                return ResourceManager.GetString("CLEAR ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string COMMANDS {
            get {
                return ResourceManager.GetString("COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Name.
        /// </summary>
        internal static string COMPONENT_NAME {
            get {
                return ResourceManager.GetString("COMPONENT NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string COMPONENTS {
            get {
                return ResourceManager.GetString("COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from User.
        /// </summary>
        internal static string COPY_FROM_USER {
            get {
                return ResourceManager.GetString("COPY FROM USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        internal static string CREATE_NEW_USER {
            get {
                return ResourceManager.GetString("CREATE NEW USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Events.
        /// </summary>
        internal static string CURRENT_EVENTS {
            get {
                return ResourceManager.GetString("CURRENT EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string DELETE_USER {
            get {
                return ResourceManager.GetString("DELETE USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DISABLE {
            get {
                return ResourceManager.GetString("DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Button Pressed.
        /// </summary>
        internal static string EMERGENCY_BUTTON_PRESSED {
            get {
                return ResourceManager.GetString("EMERGENCY BUTTON PRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string END_TIME {
            get {
                return ResourceManager.GetString("END TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faults.
        /// </summary>
        internal static string FAULTS {
            get {
                return ResourceManager.GetString("FAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FULL_NAME {
            get {
                return ResourceManager.GetString("FULL NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grinding.
        /// </summary>
        internal static string GRINDING {
            get {
                return ResourceManager.GetString("GRINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GROUPS {
            get {
                return ResourceManager.GetString("GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged.
        /// </summary>
        internal static string LOGGED {
            get {
                return ResourceManager.GetString("LOGGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Map.
        /// </summary>
        internal static string MACHINE_MAP {
            get {
                return ResourceManager.GetString("MACHINE MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string MAINTENANCE {
            get {
                return ResourceManager.GetString("MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        internal static string MANAGE_USER {
            get {
                return ResourceManager.GetString("MANAGE USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MESSAGES {
            get {
                return ResourceManager.GetString("MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Alarms or Messages.
        /// </summary>
        internal static string NO_ALARMS_OR_MESSAGES {
            get {
                return ResourceManager.GetString("NO ALARMS OR MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Local Disconnect.
        /// </summary>
        internal static string OPEN_LOCAL_DISCONNECT {
            get {
                return ResourceManager.GetString("OPEN LOCAL DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string PARAMETERS {
            get {
                return ResourceManager.GetString("PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear PET.
        /// </summary>
        internal static string PET_CLEAR {
            get {
                return ResourceManager.GetString("PET_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the New Card on the Reader.
        /// </summary>
        internal static string PLACE_THE_NEW_CARD_ON_THE_READER {
            get {
                return ResourceManager.GetString("PLACE THE NEW CARD ON THE READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Control.
        /// </summary>
        internal static string PLANT_CONTROL {
            get {
                return ResourceManager.GetString("PLANT CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Line 2.
        /// </summary>
        internal static string PLANT_LINE_2 {
            get {
                return ResourceManager.GetString("PLANT LINE 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        internal static string PLC {
            get {
                return ResourceManager.GetString("PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string PRODUCTION {
            get {
                return ResourceManager.GetString("PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Line.
        /// </summary>
        internal static string PRODUCTION_LINE {
            get {
                return ResourceManager.GetString("PRODUCTION LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Components.
        /// </summary>
        internal static string SELECT_COMPONENTS {
            get {
                return ResourceManager.GetString("SELECT COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operating Mode.
        /// </summary>
        internal static string SELECT_OPERATING_MODE {
            get {
                return ResourceManager.GetString("SELECT OPERATING MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Process.
        /// </summary>
        internal static string START_PROCESS {
            get {
                return ResourceManager.GetString("START PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string START_TIME {
            get {
                return ResourceManager.GetString("START TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch View.
        /// </summary>
        internal static string SWITCH_VIEW {
            get {
                return ResourceManager.GetString("SWITCH VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synoptic page missing!.
        /// </summary>
        internal static string SYNOPTIC_PAGE_MISSING_ {
            get {
                return ResourceManager.GetString("SYNOPTIC PAGE MISSING!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Permissions.
        /// </summary>
        internal static string SYSTEM_PERMISSIONS {
            get {
                return ResourceManager.GetString("SYSTEM PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        internal static string TRENDS {
            get {
                return ResourceManager.GetString("TRENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UNDO {
            get {
                return ResourceManager.GetString("UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string USER_MANAGEMENT {
            get {
                return ResourceManager.GetString("USER MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string USER_NAME {
            get {
                return ResourceManager.GetString("USER NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string USERS {
            get {
                return ResourceManager.GetString("USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless Card.
        /// </summary>
        internal static string WIRELESS_CARD {
            get {
                return ResourceManager.GetString("WIRELESS CARD", resourceCulture);
            }
        }
    }
}
